### ISSUE TITLE
Certificates in the 'System' keychain in OS X are not read

### ISSUE THREAD

**Issue by noinia** [vincenthz/hs-certificate#49]
OS X (10.10 Yosemite) distinguishes between 'System', and 'System Roots' keychains. If you manually add a CA (to be used for the whole system) they are added to the 'System' keychain. Since System.X509.MacOSX adds only the certificates from the 'System Roots' keychain, these are not picked up.  I would argue that the certificates from the 'System' keychain should also be read and added by System.X509.MacOSX. Could we add reading those? 

The location for the System keychain is '/Library/Keychains/System.keychain'.

**Comment by jystic** [comment]
:+1: I'm running in to this problem right now.
