### ISSUE TITLE
x509-validation-1.6.1 has syntax errors in Haddock comments

### ISSUE THREAD

**Issue by peti** [vincenthz/hs-certificate#62]
Citing from http://hydra.cryp.to/build/1148246/nixlog/1/raw:

~~~~
Data/X509/Validation.hs:360:82:
    parse error on input ‘-- * is always invalid’
~~~~~

**Comment by vincenthz** [comment]
Thanks fixed. I wonder if that's a bug in the haddock parser, as this shouldn't be a place for a markup.

**Comment by peti** [comment]
Will you release a new version to Hackage?

**Comment by vincenthz** [comment]
sure why not.
