### ISSUE TITLE
Compile error : x509-1.6.1    DistinguishedName.hs:77:37

### ISSUE THREAD

**Issue by habbler** [vincenthz/hs-certificate#67]
Under GHC-7.8.4

Preprocessing library x509-1.6.1...
[ 1 of 13] Compiling Data.X509.OID    ( Data\X509\OID.hs, dist\build\Data\X509\OID.o )
[ 2 of 13] Compiling Data.X509.Internal ( Data\X509\Internal.hs, dist\build\Data\X509\Internal.o )
[ 3 of 13] Compiling Data.X509.DistinguishedName ( Data\X509\DistinguishedName.hs, dist\build\Data\X509\DistinguishedName.o )

Data\X509\DistinguishedName.hs:77:37:
    No instance for (Control.Monad.Error.Class.MonadError
                       [Char] ParseASN1)
      arising from a use of throwError
    In the expression:
      throwError ("expecting [OID,String] got " ++ show s)
    In a case alternative:
        _ -> throwError ("expecting [OID,String] got " ++ show s)
    In a stmt of a 'do' block:
      case s of {
        [OID oid, ASN1String cs] -> return (oid, cs)
        _ -> throwError ("expecting [OID,String] got " ++ show s) }

**Comment by vincenthz** [comment]
you need to use x509 > 1.6.2. not sure why you have a latest version of asn1-parse, but not the latest version of x509.
